### ISSUE TITLE
MvvMCross Plugin > System.NullReferenceException on _fingerprint.AuthenticateAsync()

### ISSUE THREAD

**Issue by ehuna** [smstuebe/xamarin-fingerprint#71] opened 2017-07-14 21:29 UTC
## Steps to reproduce

1. Using Xamarin Forms, MvvmCross, and MvvmCross.Plugins.Fingerprint
2. Call _fingerprint.AuthenticateAsync(authenticationReason)
3. Get a "System.NullReferenceException".

## Expected behavior
No Exception, since according to the docs -

"Set the resolver of the current Activity
Skip this, if you use the MvvMCross Plugin or don't use the dialog."

## Actual behavior
The exception below occurs.

## Workaround
Add the line -
            CrossFingerprint.SetCurrentActivityResolver(() => CrossCurrentActivity.Current.Activity);
to MvxFormsApplicationActivity.OnCreate().

## Possible Solution
Update the documentation to add the above line to MvxFormsApplicationActivity.OnCreate(Bundle bundle)

### Crashlog

"System.NullReferenceException: Object reference not set to an instance of an object.\n  at Plugin.Fingerprint.Dialog.FingerprintDialogFragment+<ShowAsync>d__19.MoveNext () [0x0002f] in C:\\Projekte\\xamarin-fingerprint\\src\\Plugin.Fingerprint.Android\\Dialog\\FingerprintDialogFragment.cs:96 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter`1[
TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at Plugin.Fingerprint.Contract.AndroidFingerprintImplementationBase+<NativeAuthenticateAsync>d__0.MoveNext () [0x00042] in C:\\Projekte\\xamarin-fingerprint\\src\\Plugin.Fingerprint.Android\\Contract\\AndroidFingerprintImplementationBase.cs:17 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.Compi
lerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at Plugin.Fingerprint.Abstractions.FingerprintImplementationBase+<AuthenticateAsync>d__1.MoveNext () [0x000b3] in C:\\Projekte\\xamarin-fingerprint\\src\\Plugin.Fingerprint.Abstractions\\FingerprintImplementationBase.cs:18 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at System.Runtime.
CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 \n  at MYPROJECT.Core.Services.Authentication.FingerprintService+<Authenticate>d__7.MoveNext () [0x00067] in C:\\code\\stash\\MYPROJECT\\srcm\\MYPROJECT.Core\\Services\\Authentication\\FingerprintService.cs:48 "

## Configuration

  <package id="MvvmCross.Plugins.Fingerprint" version="1.4.5" targetFramework="portable45-net45+win8+wp8+wpa81" />

  Android Emulator 24x86

**Comment by smsissuechecker** [comment] 2017-07-14 21:29
Hi @ehuna,

I'm the friendly issue checker.
It seems like (37.50 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by ehuna** [comment] 2017-07-14 21:30
Btw, thank you for this plugin - it is amazing!

**Comment by smstuebe** [comment] 2017-07-14 22:00
You don't need the CrossCurrentActivity when you use MvvMCross. 
Have a look at
https://github.com/smstuebe/xamarin-fingerprint/blob/master/src/MvvmCross.Plugins.Fingerprint.Android/Plugin.cs

`CrossFingerprint.SetCurrentActivityResolver(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);` 

does exactly the same. Do you have the bootstrap files in your project?

**Comment by ehuna** [comment] 2017-07-14 22:31
Yes, the bootstrap files where added when I executed 'Install-Package MvvmCross.Plugins.Fingerprint'

The build action for FingerprintPluginBootstrap.cs is set to 'Compile'

Hmm... not sure what I'm doing wrong (?)

Thanks!

**Comment by smstuebe** [comment] 2017-07-16 21:07
dupe of #64

**Closed by smstuebe** 2017-07-16 21:07 UTC
Labels: duplicate
