### ISSUE TITLE
Migrate to BiometricPrompt from FingerprintManager

### ISSUE THREAD

**Issue by AndreaMinato** [smstuebe/xamarin-fingerprint#136] opened 2019-06-28 11:05 UTC
Fingerprint manager has been deprecated with API Level 28 and should be replaced by BiometricPrompt in order to provide more consistent behavior and UI between apps.
This will benefit also the package since it would enable bio-metrics other than Fingerprint.

>This class was deprecated in API level 28.
>See BiometricPrompt which shows a system-provided dialog upon starting authentication. In a world where devices may have different types of biometric authentication, it's much more realistic to have a system-provided authentication dialog since the method may vary by vendor/device. 

[FingerprintManager](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager)
[BiometricPrompt ](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.html)

I don't believe that the steps are necessary but i want to follow the template
## Steps to reproduce

1. Followed README.md procedure

2. Opened the Fingerprint dialog

3. Authenticated

## Expected behavior
A system UI dialog should appear

## Actual behavior
It appear the default provided dialog

### Crashlog

No crash, just a request

## Configuration

**Version of the Plugin:** 1.4.9

**Platform:** Android9.0

**Device:** Nokia 7 Plus

**Comment by smsissuechecker** [comment] 2019-06-28 11:05
Hi @AndreaMinato,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by smstuebe** [comment] 2019-06-28 18:00
Is already on a feature branch. the problem is backward compatibility, because Xamarin doesn't support android-x yet :< I'll have a look

**Comment by AndreaMinato** [comment] 2019-07-01 13:18
I see that they are working on an androidX implementation 
https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX#android-support---androidx-roadmap

But I wasn't able to find any clue on the roadmap completion nor any ETA.

Also I'm afraid that migrating to AndroidX will force developer to replace every Support Libraries.

What are your thoughts?

**Comment by smstuebe** [comment] 2019-07-01 14:42
Yes they are working heavily on it. I know something, but can't say it.
androidx is the future.
But I think in the beginning nobody will be forced. I'll see how to handle this in the meantime. Translate the dialog from the android-x Java to C#. Should not be too much work

**Comment by kspearrin** [comment] 2019-08-16 16:50
I got this email from Google today:

> I hope all is well with you! Your apps (xxxxxxxxxxx) have recently 
been identified by Google as part of a list of top apps that have not yet 
implemented the BiometricPrompt API introduced in Android P. We are 
reaching out to ensure that you are aware that with the introduction of the 
next wave of Android devices starting in Q4 2019, your customers may have 
fundamental issues logging into your app across millions of devices unless 
you update your app to support the BiometricPrompt API.
>
>To address this urgent issue, we recommend the following resources to help 
get your app up-to-date:
>https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/samples/BiometricDemos/
>https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt
>https://android-developers.googleblog.com/2018/06/better-biometrics-in-android-p.html
>
>We have lined up technical resources and support to help you address any 
technical issues or questions you may have as you start migrating to the 
new API. Because of the launch of new devices happening in Q4 2019, we’re 
asking that partners address this issue by October 1, 2019.
>
> BACKGROUND
>In the last 1-2 years, there has been a large shift across Android OEMs 
utilizing new forms of biometric authentication including in-display 
fingerprint sensors and 3D face authentication systems. Previously, when 
discrete fingerprint sensors were the only forms of authentication in 
Android, developers could call FingerprintManager and provide their own 
custom UI that would work across all devices (since the fingerprint sensor 
was a common hardware experience). With in-display fingerprint and face 
authentication, however, developers would need to provide a custom UI for 
each and every device implementation, which is not scalable.
>
> To address this, the BiometricPrompt API was introduced in Android P, which 
shifted the biometric experience to a system provided dialog, with a common 
set of text field inputs and configurations provided by developers. 
Utilizing this, developers can simply call BiometricPrompt for their 
various payment / sign-in experiences, and have universal support across 
all Android devices for whatever the native biometric is on the device.
>
> Many app developers are still utilizing FingerprintManager API. Unless app 
developers adopt the new BiometricPrompt API (introduced in P), their 
authentication experiences will not work on devices leveraging new forms of 
biometrics that will begin launching in Q4 2019. This means that apps will 
have a significant increase in friction for sign-ins, transactions, and 
purchases across some of the biggest Android OEMs.

**Comment by tranb3r** [comment] 2019-08-20 10:04
Now that androidx is in preview for xamarin, is it possible to do the migration to biometricprompt ?

**Comment by smstuebe** [comment] 2019-08-20 12:10
@tranb3r I already had a look. Not all android-x packages are in the preview :(
I already forked the android-x repo...

**Comment by tranb3r** [comment] 2019-08-20 12:32
@smstuebe
What exactly is missing in android-x, and is somebody from the xamarin team aware of it / working on it already ?
Can we expect a new release of the plugin soon ?
Also, if you have more information, could you please clarify your plans for the future of this plugin ?

**Comment by smstuebe** [comment] 2019-08-20 12:34
@tranb3r the BiometricPrompt android-x packages was missing the last time I had a look.
I think I'll release an alpha with biometric prompt without android-x and then proceed

**Comment by tranb3r** [comment] 2019-09-23 14:33
@smstuebe Any progress?

**Comment by lechuckcaptain** [comment] 2019-10-17 13:35
Moving to BiometricPrompt seems more important now that new Google's Pixel 4 doesn't have any fingerprint scanner at all. Any idea how and if this will be supported soon?

**Comment by joshykautz** [comment] 2019-11-12 22:03
I'm looking forward to using BiometricPrompt for exactly the same reason that @lechuckcaptain mentioned - Google Pixel 4 is out and uses different types of authentication. Thanks for the great tool @smstuebe !!!

**Comment by smstuebe** [comment] 2019-11-13 21:33
@tranb3r @joshykautz @lechuckcaptain @kspearrin @AndreaMinato 
https://github.com/smstuebe/xamarin-fingerprint/issues/151

**Closed by smstuebe** 2019-11-13 21:33 UTC
