### ISSUE TITLE
UWP build, missing file

### ISSUE THREAD

**Issue by ronpf** [smstuebe/xamarin-fingerprint#45] opened 2017-02-23 20:24 UTC
When building for UWP I'm receiving this error. Using VS 2015 on Win10 machine:

Payload file 'C:\Users\[me]\.nuget\packages\Plugin.Fingerprint\1.4.2\lib\UAP10\Plugin.Fingerprint\Properties\Plugin.Fingerprint.UWP.rd.xml' does not exist.

**Comment by smsissuechecker** [comment] 2017-02-23 20:24
Hi @ronpf,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by smstuebe** [comment] 2017-02-24 19:14
Do you have a sample project?

**Comment by ronpf** [comment] 2017-02-24 20:15
Attached is an example project.

The Plugin is being installed to and there are files in
C:\Users\RFreschi\.nuget\packages\Plugin.Fingerprint\1.4.2\lib\UAP10
But the C:\Users\RFreschi\.nuget\packages\Plugin.Fingerprint\1.4.2\lib\UAP10\Plugin.Fingerprin\Properties dir does not exist
Nor does the file C:\Users\RFreschi\.nuget\packages\Plugin.Fingerprint\1.4.2\lib\UAP10\Plugin.Fingerprint\Properties\Plugin.Fingerprint.UWP.rd.xml
I’m installing the plugin using the Visual Studio 2015 Nuget Manager for the each project

**Comment by tchadwick** [comment] 2017-03-23 23:03
Me too!

**Comment by ronpf** [comment] 2017-03-24 21:40
@tchadwick  thanks that did the trick

**Comment by tchadwick** [comment] 2017-03-24 21:46
@smstuebe if you add the plugin via the nuget package, the issue is immediately present.  It appears that the Properties\Plugin.Fingerprint.UWP.rd.xml is not being included in the Nuget package.

**Comment by smstuebe** [comment] 2017-03-24 22:06
Hey guys, I'll look at the issue at Sunday or next week :)

**Comment by smstuebe** [comment] 2017-03-30 01:06
should be fixed in 1.4.3

**Comment by tchadwick** [comment] 2017-03-31 14:30
@smstuebe This is confirmed fixed, thank you for a great plugin!

**Closed** 2017-03-31 14:31 UTC
