### ISSUE TITLE
Fingerprint does not exist in the namespace 'Plugin' errors when I upgrade Visual Studio for Xcode 11 Previews to support iOS 13

### ISSUE THREAD

**Issue by umeshdhuri1048** [smstuebe/xamarin-fingerprint#146] opened 2019-10-01 15:30 UTC
<img width="645" alt="Screenshot 2019-09-25 at 2 11 18 PM" src="https://user-images.githubusercontent.com/46932200/65976931-994d9c00-e48e-11e9-92cb-de8fa6eb3f5f.png">
I am getting below errors when I upgrade Visual Studio for Xcode 11 Previews to support iOS 13.

Error CS0234: The type or namespace name 'Fingerprint' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)
Error CS0246: The type or namespace name 'AuthenticationRequestConfiguration' could not be found (are you missing a using directive or an assembly reference?) (CS0246)
Below are the visual studio details Visual Studio for Mac version 8.3 Mono Freamwork MDK : Mono 6.4.0 Xamarin.Android Version : 10.0.0.43 Xamarin.iOS Version : 13.2.0.42 Mac OS X : 10.14.6

Thanks in advance.

**Comment by smsissuechecker** [comment] 2019-10-01 15:30
Hi @umeshdhuri1048,

I'm the friendly issue checker.
It seems like (100.00 %) you haven't used our issue template :cry: I think it is very frustrating for the repository owners, if you ignore them.

If you think it's fine to make an exception, just ignore this message.
**But if you think it was a mistake to delete the template, please close the issue and create a new one.**

Thanks!

**Comment by Doxoh** [comment] 2019-10-04 15:03
I have the same error, but did not found a solution currently

**Comment by streinhard** [comment] 2019-10-10 12:01
Same issue over here. Seems to be a Mac only issue, it works on Windows. I can browse the Assembly with Assembly Browser though. Is this a Xamarin bug?

**Comment by alvynfash** [comment] 2019-10-14 16:47
To fix this, change the mono .Net Runtimes to <= 5.20.1.12 as Mono 6.x series are incompatible

**Comment by Doxoh** [comment] 2019-10-15 15:58
@alvynfash , thanks. I changed it to Mono 5.18.1.3 but nothing changed. I get the same error

**Comment by alvynfash** [comment] 2019-10-15 17:23
@Doxoh After setting the mono version in preferences, try restarting vsmac to ensure changes are used. Otherwise, downgrade xamarin.ios to version 12.4.0.64. 

Side note, successful builld with xcode 11.1 and updated xamarin.ios as long as proj is run with monoFranework <=5.20.1.12.

Goodluck

**Comment by Doxoh** [comment] 2019-10-15 20:21
@alvynfash Thanks, after restart it's worked.
Thanks

**Comment by alvynfash** [comment] 2019-10-15 23:26
@Doxoh you're welcome, don't forget to thumbs up 👍

**Comment by pamela032709** [comment] 2019-11-06 16:14
@Doxoh  can you please explain to me how you fix it step by step . if possible. 
My current settings are visual studio 2019 and latest Xcode

**Comment by alvynfash** [comment] 2019-11-06 16:22
@pamela032709 Launch visual studio => Preferences => Projects => .NetRuntime => Select a mono version <= <=5.20.1.12

**Comment by pamela032709** [comment] 2019-11-06 16:43
It says that is currently running on 6.4.0.208 no more options. Thank you

**Comment by alvynfash** [comment] 2019-11-06 16:50
You can download needed version here => https://download.mono-project.com/archive/
Installing this would overwrite your existing version so get both copies and install the 5.20 version first then the 6.x.x version next. If you dnon't, vsmac would not launch as the latest vsmac 2019 requires mono version > 6.x.x to launch

**Comment by pamela032709** [comment] 2019-11-06 16:56
Thanks a lot. keep you posted

**Comment by pamela032709** [comment] 2019-11-06 16:59
@alvynfash  which one ? 
![Screen Shot 2019-11-06 at 11 58 47 AM](https://user-images.githubusercontent.com/19438031/68319765-d2c88700-008c-11ea-9396-f0c5c7f398b1.png)

**Comment by pamela032709** [comment] 2019-11-06 20:03
@alvynfash Thank you it fixed it. so the issue is not that plugin is visual studio ?

**Comment by alvynfash** [comment] 2019-11-06 21:09
It’s a workaround until the developer releases a new version built with mono v6.x or to netStandard library.

**Comment by smstuebe** [comment] 2019-11-14 13:05
There is now a prerelease that targets .netstandard 2.0 and also updates the internals to the latest (and hopefully greatest) stuff :)

**Comment by janagan007** [comment] 2020-01-07 07:11
I have the same error, but did not found a solution currently

**Comment by janagan007** [comment] 2020-01-07 07:12
> To fix this, change the mono .Net Runtimes to <= 5.20.1.12 as Mono 6.x series are incompatible on vsmac

I didn't understand what you are saying ?
Sorry 😐 i'm news  to Xamarin  Forms .

**Comment by elpendor** [comment] 2020-01-22 13:43
Having the same issue here.
Installed both Mono versions but I can't choose between them. There's no NET Runtimes option to be found on VS Mac (I'm using version 8.4.2)

**Comment by streinhard** [comment] 2020-01-22 14:08
Yes, the option to switch Mono versions was removed within the latest release of VS4Mac. If you want to switch Mono Versions from VS4Mac, you have to downgrade to an older version. It's not trivial to downgrade VS4Mac as Microsoft doesn't offer any path for that. However, you can try guessing the download urls for older versions, for example:

https://dl.xamarin.com/VsMac/VisualStudioForMac-8.3.11.1.dmg

The better solution for this problem is to upgrade your Xamarin App to .NET Standard. After all, [PCLs are a thing from the past](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library) and libraries will all eventually migrate to .NET Standard.

**Comment by elpendor** [comment] 2020-01-22 18:04
> The better solution for this problem is to upgrade your Xamarin App to .NET Standard. After all, PCLs are a thing from the past and libraries will all eventually migrate to .NET Standard.

Yeah, that's not an option. I would have to upgrade MvvmCross and fix everything that's broken. But thanks anyway.

I've installed an older version and now the option is there but I can only choose 6.x (and it won't let me add the older runtime)

**Comment by streinhard** [comment] 2020-01-22 18:50
After upgrading through Visual Studio for Mac you have to reinstall older Mono Versions. What you are looking for is Mono Version 5.18.1.3:

https://download.mono-project.com/archive/5.18.1/macos-10-universal/MonoFramework-MDK-5.18.1.3.macos10.xamarin.universal.pkg

**Comment by elpendor** [comment] 2020-01-22 19:05
I did install an older runtime. What I meant to say is that it's not showing up and I can't add it manually.

![Screen Shot 2020-01-22 at 16 02 32](https://user-images.githubusercontent.com/2113610/72925103-e0f37e80-3d30-11ea-997d-8c7c9726b5c2.png)

I'm trying to add it from this folder /Library/Frameworks/Mono.framework/Versions/5.18.1/

Any ideas?

**Comment by streinhard** [comment] 2020-01-22 19:41
Check that Folder and see if it has a bin/ Folder inside. Unfortunately, upgrading VS4Mac doesn't remove the entire directory, just some subfolders.

If not you have to reinstall Mono from the link above.

**Comment by elpendor** [comment] 2020-01-22 19:44
I checked that already, only 6.x has a bin folder, the others don't.

I've reinstalled mono from the link above. Many times. Always 5.x first then 6.x, otherwise vs4mac wont open.

**Comment by elpendor** [comment] 2020-01-22 20:50
Ok, the problem seems to be related to reinstalling 6.x. After I do that, the old runtimes lose their bin folder. I get that it overwrites the "current" version but it should keep the old ones.

Is it supposed to do that or am I doing something stupid?

The only workaround I found so far is keeping VS open while I install the old mono runtime and then I can select it.

**Comment by streinhard** [comment] 2020-01-22 20:55
Welcome to the world of pain using Xamarin.Fingerprint with PCL based projects. I'm in here too ;). When you install Mono 6.x, the installer sometimes removes older Mono versions. The active mono version is just a Symlink in `/Library/Frameworks/Mono.framework/Versions` and gets changed by the installer every time.

Try the following:
1. After Installing Mono 6.x, Install Mono 5.18.1.3 again
2. Open your Terminal
3. `cd /Library/Frameworks/Mono.framework/Versions`
4. `Check your installed versions: `ls -la`
5. Change the Symlink to your most recent version, e.g `sudo ln -sfn 6.4.0 Current`
6. VS Studio should now start again
7. Select the Mono `5.18.1.3` under Runtimes

**Comment by elpendor** [comment] 2020-01-22 21:03
Thanks, I just realized about the symlink, I was about to try the exact same thing. I'll post an update in a few minutes.

**Comment by pamela032709** [comment] 2020-01-22 22:20
I been there and is horrible. for the 2 applications with the issue I had
to redo de whole applications using .net .
I tried everything ,including change the mac version but and the end that
raises more issues. including that particular version only uses ITUNEs to
archieve and thats been deprecated by now.
plus more other issues along the way.
including incompatibility with the xamarin forms version mac and more
things.
my suggestion is not to use the plugin or just redo the whole thing.

Pamela Rios

**Comment by mrwcjoughin** [comment] 2020-01-23 04:52
Hi Everyone,

Really you must change your shared project to be .netstandard instead of PCL.

The more you kick that ball down the road the more pain you are going get with everything.

Do it, fix what you need to, and then you can move on without that pain.

There really is no other option, and the benefits far outweigh the effort in changing if it forces you to upgrade other packages like MVVMCross.

All new packages only support netstandard from what I have seen, and package maintainers are getting loath to support the PCL versions, and Microsoft its self is making it clear that we must change to netstandard, and I can totally understand everyone's position - .net is changing and it's for the better, and we must change with it to get the benefits of all what's coming.
Otherwise essentially you are staying on Windows 95 so you don't have to go through the pain to upgrade to Windows 10 - it's just not on, and slowly but surely you'll end up not being able to do anything.

**Comment by streinhard** [comment] 2020-01-23 17:43
Couldn't agree more with that statement ;)

**Comment by MuneebSaeed** [comment] 2021-08-03 19:47
> @Doxoh After setting the mono version in preferences, try restarting vsmac to ensure changes are used. Otherwise, downgrade xamarin.ios to version 12.4.0.64.
> 
> Side note, successfully buillds with xcode 11.1 and updated xamarin.ios as long as proj is run with monoFranework <=5.20.1.12.
> 
> Goodluck

Hi,
I am facing same issue and i have tried multiple VSmac versions with Mono 5x and 6x, What if after downgrading VS4mac and changed to mono 5x raise this issue?
After updating MacOS to 11.4 i'm stuck.


<img width="567" alt="Screenshot 2021-08-04 at 12 44 11 AM" src="https://user-images.githubusercontent.com/27008579/128076591-c2137000-9bc3-4a38-a6e7-fd5623a2a499.png">

**Closed** 2022-01-26 08:01 UTC
